class GovtFrom
{
		public static boolean registionFromFill(String name, String fathername, String email,long number,String password,String confgpassword)
	{
			boolean idCreated = false;
			   System.out.println("Name: " + name);
			   System.out.println("FatherName: " + fathername);
			   System.out.println("Email: " + email);
			   System.out.println("Number: " + number);
			   System.out.println("Password: " + password);
			   System.out.println("ConformPassword: " + confgpassword);
	 return idCreated;
	}
}
