class AgarbathiRunner {
    public static void main(String[] args) {
        Agarbathi ref1 = new Agarbathi();
		ref1.pooja();
        ref1.brandName = "Cycle";
        ref1.noOfSticks = 20;
        ref1.fragnance = "Sandalwood";
        ref1.price = 50.00;
        System.out.println("Brand Name: " + ref1.brandName);
        System.out.println("Number of Sticks: " +ref1.noOfSticks);
        System.out.println("Fragnance: " +ref1.fragnance);
        System.out.println("Price: " +ref1.price);
        Agarbathi ref2 = new Agarbathi();
        ref2.brandName = "Mangaldeep";
        ref2.noOfSticks = 25;
        ref2.fragnance = "Rose";
        ref2.price = 60.00;
        System.out.println("Brand Name: " + ref2.brandName);
        System.out.println("Number of Sticks: " +ref2.noOfSticks);
        System.out.println("Fragnance: " +ref2.fragnance);
        System.out.println("Price: " +ref2.price);
        Agarbathi ref3 = new Agarbathi();
        ref3.brandName = "Zed Black";
        ref3.noOfSticks = 30;
        ref3.fragnance = "Jasmine";
        ref3.price = 55.00;
		System.out.println("Brand Name: " + ref3.brandName);
        System.out.println("Number of Sticks: " +ref3.noOfSticks);
        System.out.println("Fragnance: " +ref3.fragnance);
        System.out.println("Price: " +ref3.price);
        Agarbathi ref4 = new Agarbathi();
        ref4.brandName = "Moksh";
        ref4.noOfSticks = 35;
        ref4.fragnance = "Lavender";
        ref4.price = 70.00;
        System.out.println("Brand Name: " + ref4.brandName);
        System.out.println("Number of Sticks: " +ref4.noOfSticks);
        System.out.println("Fragnance: " +ref4.fragnance);
        System.out.println("Price: " +ref4.price);
        Agarbathi ref5 = new Agarbathi();
        ref5.brandName = "Satya";
        ref5.noOfSticks = 40;
        ref5.fragnance = "Patchouli";
        ref5.price = 75.00;
        System.out.println("Brand Name: " + ref5.brandName);
        System.out.println("Number of Sticks: " +ref5.noOfSticks);
        System.out.println("Fragnance: " +ref5.fragnance);
        System.out.println("Price: " +ref5.price);
        Agarbathi ref6 = new Agarbathi();
        ref6.brandName = "Hem";
        ref6.noOfSticks = 45;
        ref6.fragnance = "Musk";
        ref6.price = 80.00;
        System.out.println("Brand Name: " + ref6.brandName);
        System.out.println("Number of Sticks: " +ref6.noOfSticks);
        System.out.println("Fragnance: " +ref6.fragnance);
        System.out.println("Price: " +ref6.price);
        Agarbathi ref7 = new Agarbathi();
        ref7.brandName = "Hari Darshan";
        ref7.noOfSticks = 50;
        ref7.fragnance = "Cedarwood";
        ref7.price = 85.00;
		System.out.println("Brand Name: " + ref7.brandName);
        System.out.println("Number of Sticks: " +ref7.noOfSticks);
        System.out.println("Fragnance: " +ref7.fragnance);
        System.out.println("Price: " +ref7.price);
        Agarbathi ref8 = new Agarbathi();
        ref8.brandName = "Bhakti";
        ref8.noOfSticks = 55;
        ref8.fragnance = "Frankincense";
        ref8.price = 90.00;
        System.out.println("Brand Name: " + ref8.brandName);
        System.out.println("Number of Sticks: " +ref8.noOfSticks);
        System.out.println("Fragnance: " +ref8.fragnance);
        System.out.println("Price: " +ref8.price);
        Agarbathi ref9 = new Agarbathi();
        ref9.brandName = "Kalpana";
        ref9.noOfSticks = 60;
        ref9.fragnance = "Myrrh";
        ref9.price = 95.00;
        System.out.println("Brand Name: " + ref9.brandName);
        System.out.println("Number of Sticks: " +ref9.noOfSticks);
        System.out.println("Fragnance: " +ref9.fragnance);
        System.out.println("Price: " +ref9.price);
        Agarbathi ref10 = new Agarbathi();
        ref10.brandName = "Patanjali";
        ref10.noOfSticks = 65;
        ref10.fragnance = "Tulsi";
        ref10.price = 100.00;
		System.out.println("Brand Name: " + ref10.brandName);
        System.out.println("Number of Sticks: " +ref10.noOfSticks);
        System.out.println("Fragnance: " +ref10.fragnance);
        System.out.println("Price: " +ref10.price);
        Agarbathi ref11 = new Agarbathi();
        ref11.brandName = "Hari Om";
        ref11.noOfSticks = 70;
        ref11.fragnance = "Neem";
        ref11.price = 105.00;
        System.out.println("Brand Name: " + ref11.brandName);
        System.out.println("Number of Sticks: " +ref11.noOfSticks);
        System.out.println("Fragnance: " +ref11.fragnance);
        System.out.println("Price: " +ref11.price);
        Agarbathi ref12 = new Agarbathi();
        ref12.brandName = "Shree";
        ref12.noOfSticks = 75;
        ref12.fragnance = "Aloe Vera";
        ref12.price = 110.00;
        System.out.println("Brand Name: " + ref12.brandName);
        System.out.println("Number of Sticks: " +ref12.noOfSticks);
        System.out.println("Fragnance: " +ref12.fragnance);
        System.out.println("Price: " +ref12.price);
        Agarbathi ref13 = new Agarbathi();
        ref13.brandName = "Chandan";
        ref13.noOfSticks = 80;
        ref13.fragnance = "Camphor";
        ref13.price = 115.00;
        System.out.println("Brand Name: " + ref13.brandName);
        System.out.println("Number of Sticks: " +ref13.noOfSticks);
        System.out.println("Fragnance: " +ref13.fragnance);
        System.out.println("Price: " +ref13.price);
        Agarbathi ref14 = new Agarbathi();
        ref14.brandName = "Surya";
        ref14.noOfSticks = 85;
        ref14.fragnance = "Mint";
        ref14.price = 120.00;
        System.out.println("Brand Name: " + ref14.brandName);
        System.out.println("Number of Sticks: " +ref14.noOfSticks);
        System.out.println("Fragnance: " +ref14.fragnance);
        System.out.println("Price: " +ref14.price);
        Agarbathi ref15 = new Agarbathi();
        ref15.brandName = "Shiv";
        ref15.noOfSticks = 90;
        ref15.fragnance = "Eucalyptus";
        ref15.price = 125.00;
        System.out.println("Brand Name: " + ref15.brandName);
        System.out.println("Number of Sticks: " +ref15.noOfSticks);
        System.out.println("Fragnance: " +ref15.fragnance);
        System.out.println("Price: " +ref15.price);
    }
}
