class ShampooRunner
{
    public static void main(String[] args)
	{
        Shampoo ref = new Shampoo(); 
		ref.washCars();
        ref.brandName = "clinicPlus";
        ref.qty = "Good";
        ref.type = "hairdry";
        ref.price = 60.00;
        ref.mgfDate = "12-06-24";
        ref.expDate = "23-07-29";

        System.out.println("brand name: " + ref.brandName);
        System.out.println("quantity: " + ref.qty);
        System.out.println("type: " + ref.type);
        System.out.println("price: " + ref.price);
        System.out.println("manufacturing date: " + ref.mgfDate);
        System.out.println("expiry date: " + ref.expDate);
		Shampoo ref1 = new Shampoo(); 
        ref1.brandName = "Handsolder";
        ref1.qty = "Good";
        ref1.type = "normal";
        ref1.price = 70.00;
        ref1.mgfDate = "16-06-22";
        ref1.expDate = "29-07-26";
		System.out.println("brand name: " + ref1.brandName);
        System.out.println("quantity: " + ref1.qty);
        System.out.println("type: " + ref1.type);
        System.out.println("price: " + ref1.price);
        System.out.println("manufacturing date: " + ref1.mgfDate);
        System.out.println("expiry date: " + ref1.expDate);
        Shampoo ref2 = new Shampoo(); 
        ref2.brandName = "silk";
        ref2.qty = "Average";
        ref2.type = "hairfool";
        ref2.price = 20.00;
        ref2.mgfDate = "09-02-24";
        ref2.expDate = "12-07-34";
        System.out.println("brand name: " + ref2.brandName);
        System.out.println("quantity: " + ref2.qty);
        System.out.println("type: " + ref2.type);
        System.out.println("price: " + ref2.price);
        System.out.println("manufacturing date: " + ref2.mgfDate);
        System.out.println("expiry date: " + ref2.expDate);
		Shampoo ref3 = new Shampoo();
		ref3.brandName = "SolderingPro";
		ref3.qty = "Excellent";
		ref3.type = "premium";
		ref3.price = 85.00;
		ref3.mgfDate = "10-05-21";
		ref3.expDate = "15-08-25";
		System.out.println("brand name: " + ref3.brandName);
        System.out.println("quantity: " + ref3.qty);
        System.out.println("type: " + ref3.type);
        System.out.println("price: " + ref3.price);
        System.out.println("manufacturing date: " + ref3.mgfDate);
        System.out.println("expiry date: " + ref3.expDate);
		Shampoo ref4 = new Shampoo();
		ref4.brandName = "SolderPro";
		ref4.qty = "Very High";
		ref4.type = "premium";
		ref4.price = 90.00;
		ref4.mgfDate = "02-11-20";
		ref4.expDate = "12-01-25";
		System.out.println("brand name: " + ref4.brandName);
        System.out.println("quantity: " + ref4.qty);
        System.out.println("type: " + ref4.type);
        System.out.println("price: " + ref4.price);
        System.out.println("manufacturing date: " + ref4.mgfDate);
        System.out.println("expiry date: " + ref4.expDate);
		Shampoo ref5 = new Shampoo();
		ref5.brandName = "HandySolder";
		ref5.qty = "Low";
		ref5.type = "normal";
		ref5.price = 50.00;
		ref5.mgfDate = "15-03-21";
		ref5.expDate = "25-05-26";
		System.out.println("brand name: " + ref5.brandName);
        System.out.println("quantity: " + ref5.qty);
        System.out.println("type: " + ref5.type);
        System.out.println("price: " + ref5.price);
        System.out.println("manufacturing date: " + ref5.mgfDate);
        System.out.println("expiry date: " + ref5.expDate);
		Shampoo ref6 = new Shampoo();
		ref6.brandName = "QuickWeld";
		ref6.qty = "High";
		ref6.type = "premium";
		ref6.price = 80.00;
		ref6.mgfDate = "07-08-22";
		ref6.expDate = "17-10-26";
		System.out.println("brand name: " + ref6.brandName);
        System.out.println("quantity: " + ref6.qty);
        System.out.println("type: " + ref6.type);
        System.out.println("price: " + ref6.price);
        System.out.println("manufacturing date: " + ref6.mgfDate);
        System.out.println("expiry date: " + ref6.expDate);
		Shampoo ref7 = new Shampoo();
		ref7.brandName = "ProSolder";
		ref7.qty = "Very High";
		ref7.type = "standard";
		ref7.price = 70.00;
		ref7.mgfDate = "25-12-21";
		ref7.expDate = "05-03-26";
		System.out.println("brand name: " + ref7.brandName);
        System.out.println("quantity: " + ref7.qty);
        System.out.println("type: " + ref7.type);
        System.out.println("price: " + ref7.price);
        System.out.println("manufacturing date: " + ref7.mgfDate);
        System.out.println("expiry date: " + ref7.expDate);
		Shampoo ref8 = new Shampoo();
		ref8.brandName = "MegaWeld";
		ref8.qty = "Medium";
		ref8.type = "normal";
		ref8.price = 60.00;
		ref8.mgfDate = "30-06-23";
		ref8.expDate = "10-09-27";
		System.out.println("brand name: " + ref8.brandName);
        System.out.println("quantity: " + ref8.qty);
        System.out.println("type: " + ref8.type);
        System.out.println("price: " + ref8.price);
        System.out.println("manufacturing date: " + ref8.mgfDate);
        System.out.println("expiry date: " + ref8.expDate);
		Shampoo ref9 = new Shampoo();
		ref9.brandName = "PerfectSolder";
		ref9.qty = "Very Low";
		ref9.type = "standard";
		ref9.price = 55.00;
		ref9.mgfDate = "20-10-20";
		ref9.expDate = "30-12-24";
		System.out.println("brand name: " + ref9.brandName);
        System.out.println("quantity: " + ref9.qty);
        System.out.println("type: " + ref9.type);
        System.out.println("price: " + ref9.price);
        System.out.println("manufacturing date: " + ref9.mgfDate);
        System.out.println("expiry date: " + ref9.expDate);
		Shampoo ref10 = new Shampoo();
		ref10.brandName = "ElectroFix";
		ref10.qty = "Medium";
		ref10.type = "premium";
		ref10.price = 85.00;
		ref10.mgfDate = "14-02-21";
		ref10.expDate = "24-04-25";
		System.out.println("brand name: " + ref10.brandName);
        System.out.println("quantity: " + ref10.qty);
        System.out.println("type: " + ref10.type);
        System.out.println("price: " + ref10.price);
        System.out.println("manufacturing date: " + ref10.mgfDate);
        System.out.println("expiry date: " + ref10.expDate);
		Shampoo ref11 = new Shampoo();
		ref11.brandName = "WeldExpert";
		ref11.qty = "High";
		ref11.type = "normal";
		ref11.price = 65.00;
		ref11.mgfDate = "09-05-22";
		ref11.expDate = "19-07-26";
		System.out.println("brand name: " + ref11.brandName);
        System.out.println("quantity: " + ref11.qty);
        System.out.println("type: " + ref11.type);
        System.out.println("price: " + ref11.price);
        System.out.println("manufacturing date: " + ref11.mgfDate);
        System.out.println("expiry date: " + ref11.expDate);
		Shampoo ref12 = new Shampoo();
		ref12.brandName = "UltraSolder";
		ref12.qty = "Low";
		ref12.type = "premium";
		ref12.price = 75.00;
		ref12.mgfDate = "18-07-21";
		ref12.expDate = "28-09-25";
		System.out.println("brand name: " + ref12.brandName);
        System.out.println("quantity: " + ref12.qty);
        System.out.println("type: " + ref12.type);
        System.out.println("price: " + ref12.price);
        System.out.println("manufacturing date: " + ref12.mgfDate);
        System.out.println("expiry date: " + ref12.expDate);
		Shampoo ref13 = new Shampoo();
		ref13.brandName = "SolderElite";
		ref13.qty = "Very High";
		ref13.type = "normal";
		ref13.price = 70.00;
		ref13.mgfDate = "22-11-22";
		ref13.expDate = "02-02-27";
		System.out.println("brand name: " + ref13.brandName);
        System.out.println("quantity: " + ref13.qty);
        System.out.println("type: " + ref13.type);
        System.out.println("price: " + ref13.price);
        System.out.println("manufacturing date: " + ref13.mgfDate);
        System.out.println("expiry date: " + ref13.expDate);
		Shampoo ref14 = new Shampoo();
		ref14.brandName = "HandyWeld";
		ref14.qty = "Medium";
		ref14.type = "standard";
		ref14.price = 60.00;
		ref14.mgfDate = "05-03-23";
		ref14.expDate = "15-05-27";
		System.out.println("brand name: " + ref14.brandName);
        System.out.println("quantity: " + ref14.qty);
        System.out.println("type: " + ref14.type);
        System.out.println("price: " + ref14.price);
        System.out.println("manufacturing date: " + ref14.mgfDate);
        System.out.println("expiry date: " + ref14.expDate);
		Shampoo ref15 = new Shampoo();
		ref15.brandName = "QuickSolder";
		ref15.qty = "High";
		ref15.type = "premium";
		ref15.price = 80.00;
		ref15.mgfDate = "17-09-20";
		ref15.expDate = "27-11-24";
		System.out.println("brand name: " + ref15.brandName);
        System.out.println("quantity: " + ref15.qty);
        System.out.println("type: " + ref15.type);
        System.out.println("price: " + ref15.price);
        System.out.println("manufacturing date: " + ref15.mgfDate);
        System.out.println("expiry date: " + ref15.expDate);
		

	
	}
}

	

	
	